### ISSUE TITLE
AReaL pic

### ISSUE THREAD

**Issue by lowdy1** [lowdy1/lowdy1.github.io#1]

**Comment by lowdy1** [comment]
```
# 安装torch以及torch_npu 推荐版本python3.10+, pytorch2.6+, torch_npu2.6+
# 推荐版本中无需显式 import torch_npu
pip install torch
pip install torch-npu #only for Ascend 
```
```
# 配置torchtitan
git clone https://github.com/pytorch/torchtitan
cd torchtitan
pip install -r requirements.txt
```
```
# 下载llama-3.1-8B tokenizer
python scripts/download_tokenizer.py --repo_id meta-llama/Llama-3.1-8B --hf_token=...
```
```
# 单机8卡运行训练脚本
CONFIG_FILE="./torchtitan/models/llama3/train_configs/llama3_8b.toml" ./run_train.sh
```

**Comment by lowdy1** [comment]
<img width="633" height="246" alt="Image" src="https://github.com/user-attachments/assets/28b510ad-8ea3-4743-9492-75ecd2668413" />

**Comment by lowdy1** [comment]
<img width="526" height="154" alt="Image" src="https://github.com/user-attachments/assets/6fdbafdf-7f53-483c-83d3-b68823e8ea3b" />

**Comment by lowdy1** [comment]
<img width="574" height="143" alt="Image" src="https://github.com/user-attachments/assets/978b6257-1bc0-490e-96f6-8bc060e11b64" />

**Comment by lowdy1** [comment]
<img width="3158" height="831" alt="Image" src="https://github.com/user-attachments/assets/8e8ae901-8ecd-46e7-a6a4-24f858b8b6af" />

**Comment by lowdy1** [comment]
<img width="1428" height="717" alt="Image" src="https://github.com/user-attachments/assets/39e4eb6a-9cae-431b-984e-8ff6a634fb7b" />

**Comment by lowdy1** [comment]
```
kind: Config
apiVersion: v1
preferences: {}
clusters:
  - name: internalCluster
    cluster:
      server: https://172.22.0.191:5443
      certificate-authority-data: >-
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUREekNDQWZlZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFwTVJrd0Z3WURWUVFLRXhCRFEwVWcKVkdWamFHNXZiRzluYVdWek1Rd3dDZ1lEVlFRREV3TkRRMFV3SGhjTk1qUXdNekUxTURNeU56SXpXaGNOTkRRdwpNekUxTURNeU56SXpXakFwTVJrd0Z3WURWUVFLRXhCRFEwVWdWR1ZqYUc1dmJHOW5hV1Z6TVF3d0NnWURWUVFECkV3TkRRMFV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRFgzZjhGenZTTmtCK04KLzlPREdYMXcvTDBWZlMrZE5pcjhaeUY2TjBHQUFQZDdaU2lxZHYvR3o0eS9kSTVEMXJHdktBRlYvY3dLbnJseAplTXViL1dOcjhpeTE1U1l5enVSUGh3cDRmSExOUFdtaWxSRS9QVVA2c1ZQU0JuQWJXc3RyNjRRbmZSZ3FQbjhLCndtYTgzVG1LMVEzTFQwWWwwOG16b2p1QXZ5UC9SMWZBQ2gxNVUwV25pRU5HTWJVZ3BaMWh1Vmt1QXlEdHB0N2gKS0xnem9hemxxZXNqb3VvM0phSWZkNDVhb2JxQWZOT2xWdittb0EzNU02NW95VnZQdlFoOFBqVEFQa1NRTlBHTQpNem9nMnhtV1pKWHhHQWxuaFNMYU13MU5LbWpueVBTaWtiSHVVMStRMGhuOGwxbUxNdXY4Rm1nc29ySENUeWd1CmpjSWdUQWpIQWdNQkFBR2pRakJBTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQQmdOVkhSTUJBZjhFQlRBREFRSC8KTUIwR0ExVWREZ1FXQkJSQjdSME1oZjdaUzk4aUN5RFlENVZaVm1ZU0p6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQwpBUUVBVHUwc21venBGMjBHYWluSkdLZ0VWbVo1cmNpcHlITk9tbHFrWHE5V3BQRVloNXVvSC85YXlZdjVuNjV6Cmp5NlVBQVh4ZFR6UUx0dDcrc2pueW13dkhOVzFGeUhNWE90YVArc2xpSlJyeVdEWXMrcFR2UXlwYi9RSXlUUzcKWlVKOFhpZlJxTGdpVkR3cXBDcm9Ic0VqUnFuSmNlTUdXT2xhOVNPUjBoV2p3YTFrU0w1TFVDZ01vSEJLNS9LdApwVTJkdGlSV05icEdxZUJBbS9HdmY5bDdDWktvMmg4K2t0OG9WeU1jOHRlRDhvdkoxdFliVWFyK0M3MjJVVi80ClZwR3pURUJzNjBVTmU0VnI2NWtTc0lLRUlKS3VPQVlSS2VvdEpTOFZXZFpFVitJcUpDUktwUU5mS0x6MmowVFoKUkYrYTdqaHoxUU5TbEpTSE5JZGNlUEtjd1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  - name: externalCluster
    cluster:
      server: https://1.95.7.28:5443
      insecure-skip-tls-verify: true
  - name: externalClusterTLSVerify
    cluster:
      server: https://1.95.7.28:5443
      certificate-authority-data: >-
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUREekNDQWZlZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFwTVJrd0Z3WURWUVFLRXhCRFEwVWcKVkdWamFHNXZiRzluYVdWek1Rd3dDZ1lEVlFRREV3TkRRMFV3SGhjTk1qUXdNekUxTURNeU56SXpXaGNOTkRRdwpNekUxTURNeU56SXpXakFwTVJrd0Z3WURWUVFLRXhCRFEwVWdWR1ZqYUc1dmJHOW5hV1Z6TVF3d0NnWURWUVFECkV3TkRRMFV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRFgzZjhGenZTTmtCK04KLzlPREdYMXcvTDBWZlMrZE5pcjhaeUY2TjBHQUFQZDdaU2lxZHYvR3o0eS9kSTVEMXJHdktBRlYvY3dLbnJseAplTXViL1dOcjhpeTE1U1l5enVSUGh3cDRmSExOUFdtaWxSRS9QVVA2c1ZQU0JuQWJXc3RyNjRRbmZSZ3FQbjhLCndtYTgzVG1LMVEzTFQwWWwwOG16b2p1QXZ5UC9SMWZBQ2gxNVUwV25pRU5HTWJVZ3BaMWh1Vmt1QXlEdHB0N2gKS0xnem9hemxxZXNqb3VvM0phSWZkNDVhb2JxQWZOT2xWdittb0EzNU02NW95VnZQdlFoOFBqVEFQa1NRTlBHTQpNem9nMnhtV1pKWHhHQWxuaFNMYU13MU5LbWpueVBTaWtiSHVVMStRMGhuOGwxbUxNdXY4Rm1nc29ySENUeWd1CmpjSWdUQWpIQWdNQkFBR2pRakJBTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQQmdOVkhSTUJBZjhFQlRBREFRSC8KTUIwR0ExVWREZ1FXQkJSQjdSME1oZjdaUzk4aUN5RFlENVZaVm1ZU0p6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQwpBUUVBVHUwc21venBGMjBHYWluSkdLZ0VWbVo1cmNpcHlITk9tbHFrWHE5V3BQRVloNXVvSC85YXlZdjVuNjV6Cmp5NlVBQVh4ZFR6UUx0dDcrc2pueW13dkhOVzFGeUhNWE90YVArc2xpSlJyeVdEWXMrcFR2UXlwYi9RSXlUUzcKWlVKOFhpZlJxTGdpVkR3cXBDcm9Ic0VqUnFuSmNlTUdXT2xhOVNPUjBoV2p3YTFrU0w1TFVDZ01vSEJLNS9LdApwVTJkdGlSV05icEdxZUJBbS9HdmY5bDdDWktvMmg4K2t0OG9WeU1jOHRlRDhvdkoxdFliVWFyK0M3MjJVVi80ClZwR3pURUJzNjBVTmU0VnI2NWtTc0lLRUlKS3VPQVlSS2VvdEpTOFZXZFpFVitJcUpDUktwUU5mS0x6MmowVFoKUkYrYTdqaHoxUU5TbEpTSE5JZGNlUEtjd1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
users:
  - name: user
    user:
      client-certificate-data: >-
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVGVENDQXYyZ0F3SUJBZ0lJUFluRW15NmVKNjB3RFFZSktvWklodmNOQVFFTEJRQXdLVEVaTUJjR0ExVUUKQ2hNUVEwTkZJRlJsWTJodWIyeHZaMmxsY3pFTU1Bb0dBMVVFQXhNRFEwTkZNQjRYRFRJMU1EZ3lNakEyTXpRMApPRm9YRFRJMU1EZ3lPVEEyTXpRME9Gb3dnYUV4ZERBUUJnTlZCQW9UQ1dOalpUcDFjMlZ5Y3pBbkJnTlZCQW9UCklESXhORGd4Tm1JM056aGxORFF5WlRKaU9UbGxabUZrWVRWak56Vm1aRFExTURjR0ExVUVDaE13T1dVd056azMKWVRjME16RXhOREpsWlRnNU9ETXdZV0UzTURoaE5UTXlPVFF0WTJWeWRDMHhOekV3TkRnM016SXdNU2t3SndZRApWUVFERXlBNVpUQTNPVGRoTnpRek1URTBNbVZsT0RrNE16QmhZVGN3T0dFMU16STVORENDQWFJd0RRWUpLb1pJCmh2Y05BUUVCQlFBRGdnR1BBRENDQVlvQ2dnR0JBTlNPM3d0NkxqUXZsQ2JDOER6Rzk4U0g2dlowVGYvY3JPTWMKTXRxMWpZUkhqRW5BRDlpVWNaWU1iVmxHbHZmK3AyK0l6M0VCVjZsM0M4blRMVVJ1ODlwUDcrREpKbjNUdTEwQQozakxlTDNBZUhiL2VHMjZLQWhxS01IaG9NRkRKN1ZVVGMxdWQzL2xOQ1JId1laVnVqeEFwcmh6V2s0MEhVOTBvCjNKcUJrSDhOV2NjL3RZdElQU3g5SjY0Mm15em5vNzRDVVpHS2tBZlNNYnFNaVdVTmpaUGE5bXZtRXVNYThCdVYKR2pmcnRFUHBkb3dUZ3pta0tDMElsc1VleVlsUHN3bDlxQmtiUXFDUVVWSGEyVXlDaG9rdGYrclRIbW9nMG9nagpENWtQOVZneTJqNnVidVlaVEZ4T1ZNVlBPUVBkT05jMlU5ZWcwemxaaHYvR2JOeHFDWVIxSVU2UDBaQUdrWkIzCjg3U2JFQi9LOXZ2ZUxVREpYV3YxT2VxTlladjE0dGtpQ1ljOTNaNVJseWJTRGVYck83QU5XdHYvZHZqeldKSVgKKzA3QU55TGlIV1g0cFVGOTZHcmhpckVjMVYwN3NrYTJ4WEthTklyMmZpMGtrdFpUN2NnUDFJSFN5NlA3dkxqUApaYVhMNGNBWkUycUZCQlJRajBPcHZMMVEyaVh1VHdJREFRQUJvMGd3UmpBT0JnTlZIUThCQWY4RUJBTUNCYUF3CkV3WURWUjBsQkF3d0NnWUlLd1lCQlFVSEF3SXdId1lEVlIwakJCZ3dGb0FVUWUwZERJWCsyVXZmSWdzZzJBK1YKV1ZabUVpY3dEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSlhPZzByVUt3aVVZYWJ4RjJuaWJSbFRqelRpQ3FwbQppdmg0dGlpeTJad2M5dHdyNmF6UHdOU1NvMUtUSnZ2ekxjVVJ0OUVIalNxRUw2R1c5STkzN29neTE3aEU2NFMzClFhaUVtZ1loeWtySXlZQkV5K05KejhnT0Q0N2lvaUFoVkVNYzdiRUZOWGQ3OThaS281U1JoamJYWFBrdnlRcGUKVmYwcStjSXloMUVvbnd6QXpZRXdxUXZLMzV5N1JFanI5Ti9pemprb0xreUNjbEo2NzZ3TlY3NkVBMzBTUmZQYQpUbm9wWkovYzlTTkc5dzY0K0wwN25LM2hIbDEwdERSVXRJaHM5SUFKejdLSmRiSlh3YWpNUEJrZUttZGdTTUg2CjFRb1dJSzFDTWMrcmpDeU81cTRFQ3dKOG44cmtZM05LMHpWU013Vlp2VG9KTW1Pd0JUOU0zLzA9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      client-key-data: >-
        LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlHNUFJQkFBS0NBWUVBMUk3ZkMzb3VOQytVSnNMd1BNYjN4SWZxOW5STi85eXM0eHd5MnJXTmhFZU1TY0FQCjJKUnhsZ3h0V1VhVzkvNm5iNGpQY1FGWHFYY0x5ZE10Ukc3ejJrL3Y0TWttZmRPN1hRRGVNdDR2Y0I0ZHY5NGIKYm9vQ0dvb3dlR2d3VU1udFZSTnpXNTNmK1UwSkVmQmhsVzZQRUNtdUhOYVRqUWRUM1NqY21vR1FmdzFaeHorMQppMGc5TEgwbnJqYWJMT2VqdmdKUmtZcVFCOUl4dW95SlpRMk5rOXIyYStZUzR4cndHNVVhTit1MFErbDJqQk9ECk9hUW9MUWlXeFI3SmlVK3pDWDJvR1J0Q29KQlJVZHJaVElLR2lTMS82dE1lYWlEU2lDTVBtUS8xV0RMYVBxNXUKNWhsTVhFNVV4VTg1QTkwNDF6WlQxNkRUT1ZtRy84WnMzR29KaEhVaFRvL1JrQWFSa0hmenRKc1FIOHIyKzk0dApRTWxkYS9VNTZvMWhtL1hpMlNJSmh6M2RubEdYSnRJTjVlczdzQTFhMi85MitQTllraGY3VHNBM0l1SWRaZmlsClFYM29hdUdLc1J6VlhUdXlScmJGY3BvMGl2WitMU1NTMWxQdHlBL1VnZExMby91OHVNOWxwY3Zod0JrVGFvVUUKRkZDUFE2bTh2VkRhSmU1UEFnTUJBQUVDZ2dHQkFNOEV1MTE5U1FUUWxoVk9aUlo4bnBITjR0ellGNk9yOU1KWgpFM3FKdW1Qc0gwa3hBdjNvVGR4YkRDRVlMQzhxMlQ0NjIvYnUzTWNUUityd2Z6VVlidTNnVHZ2NlRUL2RlSzB6CkREWTB5YlVEeit1djBiM09NaEJSS0xZTW00b0RzTi9jU3MwZkxTV3Nqcm5uQ2RPMVV5Ymx3VXNhL2Fnc1M5U3AKV0hvdTJHRzF5Z3ZTRSttc21NLzhzU251eXlGb0ZjVVlrd01TRmdkWUE5RHgwVnNYWVIxdzgvSFFxZktBcVB2awpNeDNsdGJNeTdaK3QzVy9GWHMvRmZycExxdlBPSndVWkdPdWYwSUhvdTJ6OS9XUXpLSWdKaXZLZVIxODg1YXYxClY4ekNjcDBPSlI2TG1MaXJRQ1VMdkJoek5PMEpTZjhTRC9yVWpaSDlnTWF0d0dCcklXcGxUYWthZnBVNkV2ci8Kak5tbmsxSEpXQWJYb2t6ZU85Q3B2SVIwNXFXTU5mazJON01SbzRZMEVJamRHSmJ2WEtLWmwrMDZjK2l0SnlrZApQOUZScGhzNG5VQmFlZ3dVbmtlOGFuVTdhUElaVE9YR2g1QnZqdzVadVU1bklKRm1KdFFlY3VhamdhUHZZTWVLCjN5c1FIV3p2RXA5VnpRaWxHTXEyS2RhaldoQXVPUUtCd1FEYUJYaW9SdzJPckpIUXE4QXdmclhZRFJoOVRZS2UKeW9xdTYzQ2JySUxQTVg0YllDdkxGNDY5dUdNNXNOYXErbGVUVHlUNTdSUkN2Y2doUEpocWhUeU5mdGJBY2gwUwpvWEx6NnpMVzlkdzlOOTl6SVYyUkNFaXl5YkZNbzhwbk5DeVdKNzdaSW9mT253SkV6M2VDTDRUUXVBN2ozVzh0CndINWNKUzhwOHcxSXdGVmgrK2JGbENycE01TWFmM2pUaUxDVlFoT2pOK1hiZnRyenZweGdXajNySDhObHNaQ2IKblFkMXp1ZG1FY1UrM2M4QnpYeHAwdFhkODJBTlI3TVpsNXNDZ2NFQStaWEVyanZyZllwUjNXSjVURFNaUHpuWQpFMzhZWDRJQ2hodHVRbG9MZHowaWlwQVBsVEI2YzJrczVDWm45aFBQZ0JadTRLTEdacWpUVWJkTm1wdkhPQ0FVCkl0aEV6ZldxT25BRFlQSko2eUY3S3VkNUFrbmlQS0dQYnkyTVBTNEU3aDA3d2xQVDZLdUIrZ1FHaG1zS1h5UksKcmJSZGFQUzJCRmVkZGZQUEhUbHVQRjc3SDdNemV2aUpvTUVhc1NHeHdtSWp2eVRsdHB0M2VZMU4wTzUxeGxZVgpWVE5ldE14d09jQW5oNHk5ZTVRVEEvUTQvbmFENUNCVXZEVWZpc0ZkQW9IQkFNcGIrN0xOU0ZNZDc3V3NSSlYrCmRwQVRENkQxK1lBalpIZVl4Z3RvSW4zblpUSkpvRHhBSUZnTnRlT05OS0s3Kzk4WnZhdFFGdGNmeVlxMzhJd20KSUo4QWxKbEpFWjBDUjIwSTZFWkhLMldTMzQ2LzhGVzJSNnZTc3dMOG45Z013RG1hcUhSbnJYL2xiTGlyakRSRQpvTlVOa1p5RUlqWm9EYUMvVHJoMEJPZDZ4WVZOeHRPcWcrMngxaDdwSkIvTEpvTlRNbUR6ZUNDejdNd0NKcWp6CitiYXI0N1FYREs2eklJS0RTWm9lY21LNGcvUWJZeGZoL21tbEJJa3UvSmlMY3dLQnYydzNoQkFINnhPRDVmc1gKdDRCVFRoOGI5WlIraHhMaVREWFpydlVXRmVLZG4xeDFHa3lWdUlKU0dDVFVnajh3VjhneDhlRjBzcEhRb2MvTQpxdGxlc2dLajVoYzFycCtlNVRCeFlRV29DR1RySDN4NjRQMGRDL3MrRWZNaXpLdTZTR2oyUS9MK1plTjhlZDd0CjMrWm9neGE5cGFPcmtOVHhSZnFjQXFvaURLdWZPeXp5QWZDOHdwV1BMaDJGblEwd2p1SzVxc1kyT1dQMEJObXYKYXc0c1Z1U29icGVDcm8yMkZ2THpYakJuMWNDL2MzOURaWEx2OEQvNXhNUFdSTmJsQW9IQkFJV3BKTnUzTnpkdApLMVNnNjhlT1N5Q2tNRHhtR1JvVTRJcWFRWkd2SUxNdVRxaExxSC94ZUFtUFRMSlZ5TWZWL0QwNWNrc3BXWTRMCms3TmpSak9xWHRlcDNyWjVHZjhOTWlVZGdVZHBTVDhaZ2tWdjl5ZWlyTUNhZEcrRWZVSWhISSt3OS8vbGRMYUYKdTFidjFxYVRBaFM3TVdyZ3ZCeXdIMFhQRWl2cURvTTd1dWF4VkVLcWJVWGczTVRwK3JwUlNadFNpNFVrOHl2QwpJbXJrcUVXRkJNbzBwZDZOS1M1N2IwRGhjVmduWWMrL1RlemxicW5kTHlJNkpEZ3JRWDYvY1E9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
contexts:
  - name: internal
    context:
      cluster: internalCluster
      user: user
  - name: external
    context:
      cluster: externalCluster
      user: user
  - name: externalTLSVerify
    context:
      cluster: externalClusterTLSVerify
      user: user
current-context: external
```

**Comment by lowdy1** [comment]
```
defaults:
  - ../config/deepspeed_zero@_here_
  - ../config/deepspeed_zero2@_here_
  - ../config/deepspeed_zero3@_here_
  - ../config/deepspeed_zero3_cpuoffload@_here_

hydra:
  run:
    dir: .
  output_subdir: null

num_gpus_per_node: 4

exp_name: "distill_zero3"
seed: 42
logging_dir: ./output/logs
output_dir: ./output

checkpoint_config:
  type: file_system
  output_dir: /home/lichenguang25/tmp/data/oss_bucket_0/chuye/roll/distill/models/zero3

save_steps: 100
logging_steps: 1
resume_from_checkpoint: false

student_pretrain: Qwen/Qwen2.5-0.5B-Instruct
teacher_pretrain: Qwen/Qwen2.5-1.5B-Instruct

# distill config
distill_loss_weight: 0.85
kd_objective: forward_kl
distill_on_prompt: True

sequence_length: 1024
max_grad_norm: 1.0

question_key: question_zh
answer_key: answer_zh


student:
  model_args:
    attn_implementation: fa2
    disable_gradient_checkpointing: false
    dtype: bf16
    model_type: ~
  training_args:
    learning_rate: 2.0e-5
    weight_decay: 1.0e-2
    lr_scheduler_type: constant
    per_device_train_batch_size: 1
    gradient_accumulation_steps: 1
    warmup_steps: 0
    num_train_epochs: 1
  data_args:
    template: qwen2_5
    file_name:
      - data/GSM8K_zh/GSM8K_zh.json        #https://huggingface.co/datasets/meta-math/GSM8K_zh
    preprocessing_num_workers: 4

  strategy_args:
    strategy_name: deepspeed_train
    strategy_config: ${deepspeed_zero3}
  device_mapping: list(range(0,2))

teacher:
  model_args:
    attn_implementation: fa2
    disable_gradient_checkpointing: true
    dtype: bf16
  # training_args:
  #   per_device_train_batch_size: 2   # 避免显存过高，可根据显存调节为 1~4
  data_args:
    template: qwen2_5
  strategy_args:
    strategy_name: deepspeed_infer
    strategy_config: ${deepspeed_zero3}
  device_mapping: list(range(2,4))

system_envs:
  RAY_PROFILING: "0"
```

**Comment by lowdy1** [comment]
```
defaults:
  - ../config/traj_envs@_here_
  - ../config/deepspeed_zero@_here_
  - ../config/deepspeed_zero2@_here_
  - ../config/deepspeed_zero3@_here_
  - ../config/deepspeed_zero3_cpuoffload@_here_

hydra:
  run:
    dir: .
  output_subdir: null

exp_name: "agentic_pipeline"
seed: 42
render_save_dir: ./oss_bucket_0/yali/llm/tensorboard/roll_exp/agentic_sokoban/renders/${exp_name}

#track_with: wandb
#tracker_kwargs:
#  api_key:
#  project: roll-agentic
#  name: ${exp_name}_sokoban
#  notes: "agentic_pipeline"
#  tags:
#    - agentic
#    - roll
#    - baseline

track_with: tensorboard
tracker_kwargs:
  log_dir: ./oss_bucket_0/yali/llm/tensorboard/roll_exp/agentic_sokoban

num_gpus_per_node: 4

max_steps: 128
save_steps: 10000

rollout_batch_size: 16
sequence_length: 1024

pretrain: Qwen/Qwen2.5-0.5B-Instruct

actor_infer:
  model_args:
    disable_gradient_checkpointing: true
    dtype: bf16
  generating_args:
    max_new_tokens: 128 # single-turn response length
    top_p: 0.99
    top_k: 100
    num_beams: 1
    temperature: 0.99
    num_return_sequences: 1
  data_args:
    template: qwen2_5
  strategy_args:
    strategy_name: vllm
    strategy_config:
      gpu_memory_utilization: 0.8
      block_size: 16
      load_format: auto # should set 'auto' here, because default load_format is 'dummy'
  device_mapping: list(range(0,4))

train_env_manager:
  format_penalty: -0.15 # sokoban env penalty_for_step=-0.1
  max_env_num_per_worker: 1
  num_env_groups: 1
  # under the same group, the env config and env seed are ensured to be equal
  group_size: 1
  tags: [SimpleSokoban]
  num_groups_partition: [1] # If not set, all env names divide nums equally. Under the same group, the env config and env seed (prompt) are equal in each generation


# Here, you can override variables defined in the imported envs. max_tokens_per_step: 128 in custom_env.SimpleSokoban, here replaced by 64
max_tokens_per_step: 64

custom_envs:
  SimpleSokoban:
    ${custom_env.SimpleSokoban}
  LargerSokoban:
    ${custom_env.LargerSokoban}
  SokobanDifferentGridVocab:
    ${custom_env.SokobanDifferentGridVocab}
  FrozenLake:
    ${custom_env.FrozenLake}
  FrozenLakeThink:
    ${custom_env.FrozenLakeThink}
```

**Comment by lowdy1** [comment]
```
# roll/utils/multiprocessing_serializer.py
import pickle
import pybase64
import torch

class MultiprocessingSerializer:
    @staticmethod
    def serialize(tensor: torch.Tensor, output_str: bool = False) -> bytes | str:
        """
        Serialize a torch.Tensor safely:
        - Detach, move to CPU
        - Convert to numpy
        - Pickle the numpy array
        """
        if not isinstance(tensor, torch.Tensor):
            raise TypeError("Only torch.Tensor is supported")

        arr = tensor.detach().cpu().numpy()
        data = pickle.dumps(arr, protocol=pickle.HIGHEST_PROTOCOL)

        if output_str:
            return pybase64.b64encode(data).decode("utf-8")
        return data

    @staticmethod
    def deserialize(data: bytes | str, device: str | None = None) -> torch.Tensor:
        """
        Deserialize back into torch.Tensor.
        If device is given (e.g., "cuda"), move tensor there.
        """
        if isinstance(data, str):
            data = pybase64.b64decode(data, validate=True)

        arr = pickle.loads(data)
        tensor = torch.from_numpy(arr)

        if device is not None:
            tensor = tensor.to(device)

        return tensor

```

**Comment by lowdy1** [comment]
```
defaults:
  - ../config/deepspeed_zero@_here_
  - ../config/deepspeed_zero2@_here_
  - ../config/deepspeed_zero3@_here_
  - ../config/deepspeed_zero3_cpuoffload@_here_

hydra:
  run:
    dir: .
  output_subdir: null

num_gpus_per_node: 4

exp_name: "distill_zero3"
seed: 42
logging_dir: ./output/logs
output_dir: ./output

checkpoint_config:
  type: file_system
  output_dir: /home/lichenguang25/tmp/data/oss_bucket_0/chuye/roll/distill/models/zero3

save_steps: 100
logging_steps: 1
resume_from_checkpoint: false

student_pretrain: Qwen/Qwen2.5-0.5B-Instruct
teacher_pretrain: Qwen/Qwen2.5-1.5B-Instruct

# distill config
distill_loss_weight: 0.85
kd_objective: forward_kl
distill_on_prompt: True

sequence_length: 1024
max_grad_norm: 1.0

question_key: question_zh
answer_key: answer_zh


student:
  model_args:
    attn_implementation: fa2
    disable_gradient_checkpointing: false
    dtype: bf16
    model_type: ~
  training_args:
    learning_rate: 2.0e-5
    weight_decay: 1.0e-2
    lr_scheduler_type: constant
    per_device_train_batch_size: 1
    gradient_accumulation_steps: 1
    warmup_steps: 0
    num_train_epochs: 1
  data_args:
    template: qwen2_5
    file_name:
      - data/GSM8K_zh/GSM8K_zh.json        #https://huggingface.co/datasets/meta-math/GSM8K_zh
    preprocessing_num_workers: 4

  strategy_args:
    strategy_name: deepspeed_train
    strategy_config: ${deepspeed_zero3}
  device_mapping: list(range(0,2))

teacher:
  model_args:
    attn_implementation: fa2
    disable_gradient_checkpointing: true
    dtype: bf16
  # training_args:
  #   per_device_train_batch_size: 2   # 避免显存过高，可根据显存调节为 1~4
  data_args:
    template: qwen2_5
  strategy_args:
    strategy_name: deepspeed_infer
    strategy_config: ${deepspeed_zero3}
  device_mapping: list(range(2,4))

system_envs:
  RAY_PROFILING: "0"
```
